### ISSUE TITLE
Can no longer install using library(devtools) 

### ISSUE THREAD

**Issue by jd-campbell** [TriticeaeToolbox/breeDBase.R#1]
I am trying install and use this package but I have across an error from R _(R version 4.3.0 (2023-04-21) -- "Already Tomorrow")_

> > library(devtools)
> Error in library(devtools) : there is no package called ‘devtools’

**Comment by dwaring87** [comment]
Hi @jd-campbell, I should make this more explicit in the install instructions, but you'll need to install the `devtools` package first 
 with `install.packages("devtools")`
